# Generated by Django 3.0.7 on 2020-08-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=20, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(max_length=20, verbose_name='Segundo Nombre')),
                ('primer_apellido', models.CharField(max_length=20, verbose_name='Apellido Paterno')),
                ('segundo_apellido', models.CharField(max_length=20, verbose_name='Apellido Materno')),
                ('cargo', models.CharField(max_length=20, verbose_name='Cargo')),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='Cedula')),
                ('celular', models.CharField(max_length=10, unique=True, verbose_name='Celular')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['primer_nombre'],
            },
        ),
    ]
