# Generated by Django 3.0.7 on 2020-08-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=20, verbose_name='Apellido')),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='Cedula')),
                ('celular', models.CharField(max_length=10, unique=True, verbose_name='Celular')),
                ('usuario', models.CharField(max_length=15, unique=True, verbose_name='Usuario')),
                ('contrasena', models.CharField(max_length=10, unique=True, verbose_name='Contrasena')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['nombre'],
            },
        ),
    ]
