# Generated by Django 3.0.7 on 2020-08-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('password1', models.CharField(max_length=10, verbose_name='Contrasena')),
                ('password2', models.CharField(max_length=10, verbose_name='Repetir Contrasena')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['username'],
            },
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
